import type { Level } from "../types";

export const LEVELS: Level[] = [
  // ─── 入门关卡 1-5（黑子少，无威胁） ───
  {
    id: 1,
    name: "初出茅庐",
    description: "只有几颗散落的黑子，轻松入门",
    blackStones: [
      { row: 3, col: 3 },
      { row: 5, col: 8 },
      { row: 8, col: 4 },
      { row: 10, col: 11 },
      { row: 2, col: 12 },
      { row: 12, col: 2 },
    ],
  },
  {
    id: 2,
    name: "小试牛刀",
    description: "黑子稍多，学习用技能辅助落子",
    blackStones: [
      { row: 2, col: 2 },
      { row: 4, col: 6 },
      { row: 6, col: 4 },
      { row: 7, col: 9 },
      { row: 9, col: 7 },
      { row: 11, col: 5 },
      { row: 3, col: 11 },
      { row: 12, col: 10 },
      { row: 1, col: 7 },
    ],
  },
  {
    id: 3,
    name: "崭露头角",
    description: "黑子开始形成简单聚集",
    blackStones: [
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 7, col: 7 },
      { row: 8, col: 8 },
      { row: 6, col: 11 },
      { row: 11, col: 3 },
      { row: 11, col: 4 },
      { row: 2, col: 9 },
      { row: 13, col: 8 },
    ],
  },
  {
    id: 4,
    name: "略显章法",
    description: "黑子已有两连，注意防守",
    blackStones: [
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 5, col: 7 },
      { row: 8, col: 3 },
      { row: 9, col: 3 },
      { row: 10, col: 4 },
      { row: 11, col: 9 },
      { row: 11, col: 10 },
      { row: 3, col: 12 },
      { row: 13, col: 13 },
      { row: 1, col: 1 },
      { row: 2, col: 2 },
    ],
  },
  {
    id: 5,
    name: "渐入佳境",
    description: "黑子形成活二，合理使用技能",
    blackStones: [
      { row: 6, col: 6 },
      { row: 6, col: 7 },
      { row: 7, col: 6 },
      { row: 7, col: 7 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 10, col: 10 },
      { row: 10, col: 11 },
      { row: 10, col: 12 },
      { row: 12, col: 5 },
      { row: 13, col: 5 },
      { row: 1, col: 9 },
      { row: 2, col: 9 },
      { row: 2, col: 10 },
    ],
  },

  // ─── 进阶关卡 6-10（黑子多，有三连四连威胁） ───
  {
    id: 6,
    name: "棋逢对手",
    description: "对手开始主动落子，有三连威胁",
    blackStones: [
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 7, col: 7 },
      { row: 7, col: 8 },
      { row: 7, col: 9 },
      { row: 9, col: 5 },
      { row: 9, col: 6 },
      { row: 11, col: 11 },
      { row: 11, col: 12 },
      { row: 3, col: 10 },
      { row: 4, col: 10 },
      { row: 13, col: 2 },
      { row: 2, col: 13 },
      { row: 1, col: 5 },
    ],
  },
  {
    id: 7,
    name: "如临大敌",
    description: "多处三连，必须优先防守",
    blackStones: [
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 6, col: 8 },
      { row: 6, col: 9 },
      { row: 6, col: 10 },
      { row: 8, col: 4 },
      { row: 9, col: 5 },
      { row: 10, col: 6 },
      { row: 11, col: 8 },
      { row: 11, col: 9 },
      { row: 12, col: 10 },
      { row: 2, col: 7 },
      { row: 3, col: 7 },
      { row: 13, col: 3 },
      { row: 1, col: 12 },
      { row: 2, col: 11 },
    ],
  },
  {
    id: 8,
    name: "步步为营",
    description: "密集布局，活用技能清除障碍",
    blackStones: [
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 5, col: 9 },
      { row: 5, col: 10 },
      { row: 5, col: 11 },
      { row: 5, col: 12 },
      { row: 7, col: 3 },
      { row: 8, col: 4 },
      { row: 9, col: 5 },
      { row: 10, col: 6 },
      // removed (11,7) to break the diagonal five-in-a-row: (7,3)→(8,4)→(9,5)→(10,6)→(11,7)
      { row: 7, col: 11 },
      { row: 8, col: 10 },
      { row: 9, col: 9 },
      { row: 12, col: 12 },
      { row: 13, col: 11 },
      { row: 1, col: 8 },
      { row: 2, col: 1 },
    ],
  },
  {
    id: 9,
    name: "险象环生",
    description: "多条四连迫在眉睫，用技能化解",
    blackStones: [
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 8, col: 8 },
      { row: 8, col: 9 },
      { row: 8, col: 10 },
      { row: 8, col: 11 },
      { row: 2, col: 8 },
      { row: 3, col: 9 },
      { row: 4, col: 10 },
      { row: 5, col: 11 },
      { row: 10, col: 3 },
      { row: 11, col: 3 },
      { row: 12, col: 3 },
      { row: 13, col: 3 },
      { row: 6, col: 6 },
      { row: 7, col: 5 },
      { row: 9, col: 4 },
      { row: 10, col: 10 },
      { row: 11, col: 10 },
      { row: 1, col: 13 },
      { row: 2, col: 12 },
    ],
  },
  {
    id: 10,
    name: "绝处逢生",
    description: "棋盘被黑子占据大半，需要精妙操作",
    blackStones: [
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 7 },
      { row: 2, col: 8 },
      { row: 2, col: 9 },
      { row: 2, col: 10 },
      { row: 3, col: 13 },
      { row: 4, col: 12 },
      { row: 5, col: 11 },
      { row: 6, col: 10 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 7, col: 7 },
      { row: 7, col: 8 },
      { row: 7, col: 9 },
      { row: 9, col: 3 },
      { row: 9, col: 4 },
      { row: 9, col: 5 },
      { row: 9, col: 6 },
      { row: 11, col: 9 },
      { row: 11, col: 10 },
      { row: 11, col: 11 },
      { row: 12, col: 5 },
      { row: 12, col: 6 },
      { row: 13, col: 10 },
      { row: 13, col: 11 },
      { row: 13, col: 12 },
    ],
  },
];
